# Generated by Django 4.2.15 on 2025-08-21 09:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PasswordResetToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "token",
                    models.CharField(
                        help_text="Unique token for password reset.",
                        max_length=64,
                        unique=True,
                        verbose_name="reset token",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="When the token was created.",
                        verbose_name="created at",
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        help_text="When the token expires.", verbose_name="expires at"
                    ),
                ),
                (
                    "is_used",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the token has been used.",
                        verbose_name="is used",
                    ),
                ),
                (
                    "used_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the token was used.",
                        null=True,
                        verbose_name="used at",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True,
                        help_text="IP address from which reset was requested.",
                        null=True,
                        verbose_name="IP address",
                    ),
                ),
                (
                    "user_agent",
                    models.TextField(
                        blank=True,
                        help_text="User agent string from reset request.",
                        verbose_name="user agent",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User requesting password reset.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="password_reset_tokens",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Password Reset Token",
                "verbose_name_plural": "Password Reset Tokens",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["token"], name="accounts_pa_token_affdf2_idx"),
                    models.Index(
                        fields=["user", "is_used"],
                        name="accounts_pa_user_id_023f8d_idx",
                    ),
                    models.Index(
                        fields=["expires_at"], name="accounts_pa_expires_01b447_idx"
                    ),
                ],
            },
        ),
    ]
