# Generated by Django 4.2.17 on 2025-08-26 16:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TodoList",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Name of the todo list", max_length=200),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Optional description of the todo list",
                        null=True,
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        default="#3B82F6",
                        help_text="Hex color code for UI display (e.g., #3B82F6)",
                        max_length=7,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        help_text="Owner of the todo list",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="todo_lists",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "todo_lists",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Title/summary of the task", max_length=300
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Detailed description of the task",
                        null=True,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("urgent", "Urgent"),
                        ],
                        default="medium",
                        help_text="Priority level of the task",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("todo", "Todo"),
                            ("ongoing", "Ongoing"),
                            ("done", "Done"),
                        ],
                        default="todo",
                        help_text="Current status of the task",
                        max_length=10,
                    ),
                ),
                (
                    "start_date",
                    models.DateField(
                        blank=True,
                        help_text="Date when work on the task should begin",
                        null=True,
                    ),
                ),
                (
                    "end_date",
                    models.DateField(
                        blank=True, help_text="Due date for the task", null=True
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when task was completed",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "todo_list",
                    models.ForeignKey(
                        help_text="Todo list this task belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="todos.todolist",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who owns this task",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "tasks",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="todolist",
            index=models.Index(
                fields=["user", "-created_at"], name="todo_lists_user_id_dd2218_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="todolist",
            index=models.Index(
                fields=["user", "name"], name="todo_lists_user_id_5f9a8b_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="todolist",
            constraint=models.UniqueConstraint(
                fields=("user", "name"), name="unique_user_todolist_name"
            ),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(
                fields=["todo_list", "status"], name="tasks_todo_li_a5f32b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(
                fields=["user", "end_date"], name="tasks_user_id_679419_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(
                fields=["priority", "status"], name="tasks_priorit_2b45be_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(
                fields=["end_date", "status"], name="tasks_end_dat_9f12ef_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(
                fields=["user", "status"], name="tasks_user_id_a53e17_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(
                fields=["user", "priority"], name="tasks_user_id_e06a45_idx"
            ),
        ),
    ]
