# Generated by Django 4.2.17 on 2025-09-15 13:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("todos", "0002_migrate_projects_to_todos"),
    ]

    operations = [
        migrations.AddField(
            model_name="todolist",
            name="deadline",
            field=models.DateField(
                blank=True,
                help_text="Deadline for completing the entire todo list",
                null=True,
            ),
        ),
    ]
