# Generated by Django 4.2.17 on 2025-09-15 13:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("todos", "0003_todolist_deadline"),
    ]

    operations = [
        migrations.AddField(
            model_name="todolist",
            name="is_favorite",
            field=models.BooleanField(
                default=False, help_text="Whether this todo list is marked as favorite"
            ),
        ),
    ]
