# Generated by Django 4.2.17 on 2025-09-17 04:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("todos", "0004_todolist_is_favorite"),
    ]

    operations = [
        migrations.CreateModel(
            name="Activity",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "activity_type",
                    models.CharField(
                        choices=[
                            ("todo_list_created", "Todo List Created"),
                            ("todo_list_updated", "Todo List Updated"),
                            ("todo_list_deleted", "Todo List Deleted"),
                            ("task_created", "Task Created"),
                            ("task_updated", "Task Updated"),
                            ("task_completed", "Task Completed"),
                            ("task_deleted", "Task Deleted"),
                        ],
                        help_text="Type of activity performed",
                        max_length=50,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Human-readable title of the activity", max_length=200
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Detailed description of the activity"
                    ),
                ),
                (
                    "todo_list_id",
                    models.UUIDField(
                        blank=True,
                        help_text="ID of related todo list (if applicable)",
                        null=True,
                    ),
                ),
                (
                    "todo_list_name",
                    models.CharField(
                        blank=True,
                        help_text="Name of related todo list (cached for deleted objects)",
                        max_length=200,
                    ),
                ),
                (
                    "task_id",
                    models.UUIDField(
                        blank=True,
                        help_text="ID of related task (if applicable)",
                        null=True,
                    ),
                ),
                (
                    "task_title",
                    models.CharField(
                        blank=True,
                        help_text="Title of related task (cached for deleted objects)",
                        max_length=200,
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="When the activity occurred",
                    ),
                ),
                (
                    "context",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional context data about the activity",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who performed the activity",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "todo_activities",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["user", "-timestamp"],
                        name="todo_activi_user_id_887c98_idx",
                    ),
                    models.Index(
                        fields=["activity_type", "-timestamp"],
                        name="todo_activi_activit_427883_idx",
                    ),
                    models.Index(
                        fields=["todo_list_id"], name="todo_activi_todo_li_5cd83a_idx"
                    ),
                    models.Index(
                        fields=["task_id"], name="todo_activi_task_id_49912f_idx"
                    ),
                ],
            },
        ),
    ]
