# Generated by Django 4.2.15 on 2025-08-21 10:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkflowState",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("color", models.CharField(default="#6B7280", max_length=7)),
                ("icon", models.CharField(blank=True, max_length=50)),
                ("is_initial", models.BooleanField(default=False)),
                ("is_final", models.BooleanField(default=False)),
                ("order", models.IntegerField(default=0)),
                ("auto_assign_to_creator", models.BooleanField(default=False)),
                ("require_assignee", models.BooleanField(default=False)),
                ("require_comment", models.BooleanField(default=False)),
                ("notify_stakeholders", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "workflow_states",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="WorkflowTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "entity_type",
                    models.CharField(
                        choices=[("feature", "Feature"), ("project", "Project")],
                        max_length=50,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_workflows",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "workflow_templates",
                "unique_together": {("name", "entity_type")},
            },
        ),
        migrations.CreateModel(
            name="WorkflowTransition",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("require_permission", models.CharField(blank=True, max_length=100)),
                (
                    "require_role",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("owner", "Owner"),
                            ("assignee", "Assignee"),
                            ("admin", "Admin"),
                            ("any", "Any User"),
                        ],
                        default="any",
                        max_length=50,
                    ),
                ),
                ("require_all_subtasks_complete", models.BooleanField(default=False)),
                ("require_comment", models.BooleanField(default=False)),
                ("auto_set_due_date_days", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "auto_assign_to_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="auto_assigned_transitions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "from_state",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outgoing_transitions",
                        to="workflow.workflowstate",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transitions",
                        to="workflow.workflowtemplate",
                    ),
                ),
                (
                    "to_state",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incoming_transitions",
                        to="workflow.workflowstate",
                    ),
                ),
            ],
            options={
                "db_table": "workflow_transitions",
                "unique_together": {("template", "from_state", "to_state")},
            },
        ),
        migrations.AddField(
            model_name="workflowstate",
            name="template",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="states",
                to="workflow.workflowtemplate",
            ),
        ),
        migrations.CreateModel(
            name="WorkflowRule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("trigger_condition", models.JSONField(blank=True, default=dict)),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("auto_transition", "Auto Transition"),
                            ("send_notification", "Send Notification"),
                            ("assign_user", "Assign User"),
                            ("set_due_date", "Set Due Date"),
                            ("add_comment", "Add Comment"),
                            ("webhook", "Webhook"),
                        ],
                        max_length=50,
                    ),
                ),
                ("action_config", models.JSONField(blank=True, default=dict)),
                ("is_active", models.BooleanField(default=True)),
                ("priority", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_workflow_rules",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rules",
                        to="workflow.workflowtemplate",
                    ),
                ),
                (
                    "trigger_on_state",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trigger_rules",
                        to="workflow.workflowstate",
                    ),
                ),
            ],
            options={
                "db_table": "workflow_rules",
                "ordering": ["priority", "name"],
            },
        ),
        migrations.CreateModel(
            name="WorkflowHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("entity_type", models.CharField(max_length=50)),
                ("entity_id", models.UUIDField()),
                ("comment", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "changed_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workflow_changes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "from_state",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="history_from",
                        to="workflow.workflowstate",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history",
                        to="workflow.workflowtemplate",
                    ),
                ),
                (
                    "to_state",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history_to",
                        to="workflow.workflowstate",
                    ),
                ),
                (
                    "transition",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="history",
                        to="workflow.workflowtransition",
                    ),
                ),
            ],
            options={
                "db_table": "workflow_history",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AlterUniqueTogether(
            name="workflowstate",
            unique_together={("template", "name"), ("template", "slug")},
        ),
        migrations.CreateModel(
            name="WorkflowMetrics",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("avg_time_in_state_hours", models.FloatField(default=0)),
                ("total_entries", models.IntegerField(default=0)),
                ("total_exits", models.IntegerField(default=0)),
                ("completion_rate", models.FloatField(default=0)),
                ("period_start", models.DateTimeField()),
                ("period_end", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "state",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metrics",
                        to="workflow.workflowstate",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metrics",
                        to="workflow.workflowtemplate",
                    ),
                ),
            ],
            options={
                "db_table": "workflow_metrics",
                "unique_together": {
                    ("template", "state", "period_start", "period_end")
                },
            },
        ),
    ]
